// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA95cKiLKMmgSfjRvLHj_rASIBY6gBioN0',
    appId: '1:623012888388:android:e796540516ae711bd16111',
    messagingSenderId: '623012888388',
    projectId: 'voicegrocery-fyp',
    databaseURL: 'https://voicegrocery-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'voicegrocery-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT8wPMl5ttiFWf3knignNKjpylwdTGsyw',
    appId: '1:623012888388:ios:919739b5efa12a17d16111',
    messagingSenderId: '623012888388',
    projectId: 'voicegrocery-fyp',
    databaseURL: 'https://voicegrocery-fyp-default-rtdb.firebaseio.com',
    storageBucket: 'voicegrocery-fyp.firebasestorage.app',
    androidClientId: '623012888388-ia5i0fvjvj2dk7ijflr7pnqfil8tboa9.apps.googleusercontent.com',
    iosClientId: '623012888388-1jc9j9c65uus3fleptd6tcdrp76ffc7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

}